apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.database.name }}
  labels:
    {{- include "sendy.labels" . | nindent 4 }}
spec:
  externalName: {{ .Values.database.externalName }}
  selector:
    {{- include "sendy.selectorLabels" . | nindent 4 }}
  type: ExternalName