apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "sendy.fullname" . }}
  labels:
    {{- include "sendy.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "sendy.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "sendy.selectorLabels" . | nindent 8 }}
    spec:
      serviceAccountName: {{ $.Values.serviceAccount.name }}
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            - name: SENDY_PROTOCOL
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.secrets.name }}
                  key: sendy_protocol
            - name: SENDY_FQDN
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.secrets.name }}
                  key: sendy_fqdn
            - name: MYSQL_HOST
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.secrets.name }}
                  key: db_host
            - name: MYSQL_DATABASE
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.secrets.name }}
                  key: db_name
            - name: MYSQL_USER
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.secrets.name }}
                  key: db_user
            - name: MYSQL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.secrets.name }}
                  key: db_password
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /
              port: http
          readinessProbe:
            httpGet:
              path: /
              port: http
          resources:
            {{- toYaml .Values.resources | nindent 12 }}