apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: {{ include "sendy.fullname" . }}
  labels:
    {{- include "sendy.labels" . | nindent 4 }}
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: {{ include "sendy.fullname" . }}
    kind: SecretStore
  target:
    name: {{ $.Values.secrets.name }}
    creationPolicy: Owner
  data:
  - secretKey: sendy_protocol
    remoteRef:
      key: {{ $.Values.secrets.key }}
      property: protocol
  - secretKey: sendy_fqdn
    remoteRef:
      key: {{ $.Values.secrets.key }}
      property: fqdn
  - secretKey: db_host
    remoteRef:
      key: {{ $.Values.secrets.key }}
      property: db.host
  - secretKey: db_name
    remoteRef:
      key: {{ $.Values.secrets.key }}
      property: db.name
  - secretKey: db_user
    remoteRef:
      key: {{ $.Values.secrets.key }}
      property: db.user
  - secretKey: db_password
    remoteRef:
      key: {{ $.Values.secrets.key }}
      property: db.password