apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: {{ include "sendy.fullname" . }}
spec:
  provider: aws
  parameters: 
    objects: |
      - objectName: {{ .Values.secrets.key | quote }}
        objectType: "secretsmanager"
        jmesPath:
          - path: protocol
            objectAlias: sendy_protocol
          - path: fqdn
            objectAlias: sendy_fqdn
          - path: db.host
            objectAlias: db_host
          - path: db.name
            objectAlias: db_name
          - path: db.user
            objectAlias: db_user
          - path: db.password
            objectAlias: db_password
  secretObjects:                
    - secretName: {{ .Values.secrets.name }}
      type: Opaque
      data:
        - objectName: sendy_protocol
          key: sendy_protocol
        - objectName: sendy_fqdn
          key: sendy_fqdn
        - objectName: db_host
          key: db_host
        - objectName: db_name
          key: db_name
        - objectName: db_user
          key: db_user
        - objectName: db_password
          key: db_password